services:
  - type: web
    name: bshb-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.mjs
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 4000
